name: Monthly Workflow Keepalive

on:
  schedule:
    # Runs at 00:00 UTC on the 1st of every month
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  keepalive_job:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Keep workflows alive
        uses: liskin/gh-workflow-keepalive@v2